### PR TITLE
Add before_transfer callback

### PR DESCRIPTION
**Pull request by zyura**
It allows to switch a physical transmitter chip to read or write mode.

Useful in half duplex operation when a transmitter direction is
controlled with a GPIO pin.

Example usage:

```
def switch(instrument, is_write):
    instrument.serial.flush()
    
    # pin_de is a GPIO class instance
    pin_de.set_value(is_write)

instrument = Instrument('/dev/ttyS1', 1, before_transfer=switch)  # port name, slave address (in decimal)
```

### CODE REVIEW

**Comment by pyhys** [comment]
Hi! This is interesting, and I will mention your pull request in the official documentation. However I do not think it is suitable for inclusion in mainline, simply because it will only work for really low speeds. See my measurements: https://minimalmodbus.readthedocs.io/en/stable/serialcommunication.html 

I will give at attribution to you in the AUTHORS file.

**Comment by zyura** [comment]
Ok, thanks.

It works for us on 500 MHz embedded CPU running OpenWRT with 9600 bps Modbus speed. I hope it will be useful for others.

**Comment by j123b567** [comment]
Just to note, there is already similat functionality in pyserial

https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.rs485.RS485

We are using custom serial class very similar to this RS485 which toggles GPIO instead of RTS. So much better solution woul be to allow custom serial class factory instead of reimplementing this in minimalmodbus.

We are now accessing `_` members of minimalmodbus to initialize serial port before `Instrument`, which is little bit tricky.

**Comment by CrabbyPete** [comment]
Has this commit been merged?

**Comment by j123b567** [comment]
> Has this commit been merged?

No, it has trivial solution without poluting the minimalmodbus codebase. See e.g. https://github.com/pyhys/minimalmodbus/issues/137#issuecomment-2685900902

**Pull request closed without merging**
